show_graph.py의 adjust_coordinates함수 개선
oss2024hnu/coursegraph-py pull request #370
Opened 2024-06-07 06:24 UTC by m222zu

subjects가 None일 경우, 빈 딕셔너리를 반환하도록 설정하였습니다.

2024-06-08 15:10 UTC, kyagrd commented on coursegraph/show_graph.py
> -    plt.axhline((max(plt.yticks()[0]) + min(plt.yticks()[0])) / 2, color='gray', linestyle='--')
이 부분 왜 지우는거죠???

2024-06-08 15:10 UTC, kyagrd requested changes
아마 다른 PR이 들어온 거를 먼저 머지해서 그런 거 같은데 충돌나는 거 일단 해결해 주세요.
그리고 Y축 중간 지점에 선 긋는 거 왜 기능 삭제하는거죠?

2024-06-10 00:32 UTC, kyahnu commented on coursegraph/show_graph.py
> -    plt.axhline((max(plt.yticks()[0]) + min(plt.yticks()[0])) / 2, color='gray', linestyle='--')
아 이 부분은 지울만 하네요 중앙선을 긋는 줄 알았는데 엉뚱한 선을 긋고 있어서 ...

2024-06-10 00:33 UTC, kyahnu commented on coursegraph/show_graph.py
> -    plt.axhline((max(plt.yticks()[0]) + min(plt.yticks()[0])) / 2, color='gray', linestyle='--')
충돌나는 부분만 해소하거나 아니면 충돌 해결이 더 복잡하면 취소하고 다시 최신 버전으로 fork 해서 PR 작성해 주세요

2024-06-13 05:26 UTC, closed without merging