change the computer practice subject
oss2024hnu/coursegraph-py pull request #39
Opened 2024-05-01 08:42 UTC by stayineverywhere

실습 과목 여부를 https://github.com/oss2024hnu/coursegraph-py/tree/main/data 여기에 수정하였습니다!! 실습이 있는 과목은 실습이 있다고 표시하였습니다!!

2024-05-01 20:59 UTC, kyahnu commented
그동안 먼저 있던 PR에서 같은 파일을 수정해서 conflict가 났으니 해결해 주세요

2024-05-02 01:36 UTC, stayineverywhere commented
오류 수정했습니다!!

2024-05-02 02:09 UTC, kyahnu requested changes
yaml에는 yes나 no로 나타내는 boolean형식이 있으므로 "실습 O"나 "실습 X"같은 문자열 대신에 표준적으로 제공되는 형식으로 데이터 항목을 나타내 주세요

2024-05-02 02:57 UTC, stayineverywhere commented
수정하였습니다!!

2024-05-02 19:00 UTC, merged