README.md -f dot 옵션 설명 추가
oss2024hnu/coursegraph-py pull request #438
Opened 2024-06-15 05:20 UTC by HeoSeungBeen

#405 해당 이슈에 맞추어
dot 옵션이 추가된 것에 대해 README.md 파일 수정이 이루어지지 않아 
dot 옵션 사용법에 대한 내용을 추가했습니다.

graphviz 를 설치하는 부분은 권장하지 않는 옵션으로 표현했고
다른 옵션과 달리 dot 옵션에는 추가적인 설명이 덧붙으면 좋을 것 같아
graphivz 시각화에 필요한 웹사이트를 추가함으로써 사용자들이 쉽게 접근할 수 있도록 추가했습니다.

현재 PR 요청된 파일의 README.md 파일은 .dot 옵션에 관한 것이 아니라 판단했기에 다시 작성했습니다

2024-06-15 07:25 UTC, kyagrd requested changes
아래 목록으로 나온 설명 말고 CLI를 --help 옵션으로 실행했을 때 나오는 내용(아마도 검은바탕? 백틱 3개로 블록 인용된 부분)도 함께 업데이트 해 주세요. CLI를 --help로 실행해서 나온는 명령창 복붙하면 됩니다.

2024-06-15 07:39 UTC, HeoSeungBeen commented
수정 완료했습니다.

2024-06-15 15:09 UTC, HeoSeungBeen commented
#455 
추가적으로 초록 노드와 화살표를 보이지 배경과 같아지게 수정도 했는데 
하나의 fork 된 레포지토리에서 여러개의 PR 이 익숙하지 않아 한번에 수정했습니다

2024-06-16 13:30 UTC, HeoSeungBeen commented
#456 
이슈에서 작성 된 것 처럼 그래프를 가로로 배치했습니다.

2024-06-17 06:42 UTC, merged