다른 yaml 파일도  표로 볼 수 있도록 수정했습니다.
oss2024hnu/coursegraph-py pull request #67
Opened 2024-05-02 04:30 UTC by lunatic280

__main__.py에서 실행하는 것을 좀 더 걸릴 것 같습니다

2024-05-02 07:24 UTC, lunatic280 commented
#75, #74 show_yaml파일에서 불필요한 부분 수정했습니다.

2024-05-02 11:31 UTC, lunatic280 commented
이제 __main__.py 파일에서 -s 명령어를 추가해서 
'python __main__.py -s' 를 입력하고
원하는 yaml 파일 이름을 넣으면 main.py파일에서 표를 만들어 줍니다

2024-05-03 14:25 UTC, kyahnu commented
아 전에 올렸던 같은 내용인데 ai-concept-demo에 대한 PR이 있어서 그거랑 똑같은 건 줄 알고 헷갈렸네요

2024-05-03 14:26 UTC, kyahnu requested changes
- .vscode 세팅은 포함하지 마세요
- 지금 다른 먼저 merge한 PR들이랑 conflict 나는 부분이 있기 때문에 그것도 해소해야 하고

이 두 가지를 해소해야 합니다

2024-05-03 14:29 UTC, closed without merging

2024-05-03 14:33 UTC, lunatic280 commented
네 알겠습니다